### ISSUE TITLE
Make it async

### ISSUE THREAD

**Issue by automata** [leeoniya/RgbQuant.js#20]
Are there plans to make `reduce`, `pallete`, .. asynchronous?

**Comment by leeoniya** [comment]
You could probably get away with wrapping those funcs in `setTimeout` or `requestAnimationFrame` if your goal is just to update the UI to "calculating" or similar:

```js
setTimeout(function() {
    pal = q.palette();
}, 0);
```

If you need it to be fully backgrounded, you can grab the canvas pixel data and pass it to `rgbquant` running in a web worker - it has no DOM dependencies and can accept a pixel array from the `ImageData` object.

related: #14

**Comment by Lucas-naceri** [comment]
Hi (you have 1 new message from Facebook)

**Comment by frankred** [comment]
In my oppinion does not really makes sense to make it async because its pure JS without any IO operations. 

If you want it to have it async just do the following in nodejs:

```
process.nextTick(function(){ doSomething() });
```

**Comment by leeoniya** [comment]
closing for now, feel free to re-open.

**Comment by jonnor** [comment]
'Async' might be the wrong word. What would be very desirable is to be able to chunk up the processing, such that one is only blocking the event loop for a bit at a time. This then allows to handle say HTTP requests in node.js or similar in between, instead of having to wait for the entire image to finish processing.
Ideally there are parameters that allows the consumer to decide how fine-grained the chunking should be.

**Comment by leeoniya** [comment]
if blocking the UI is the problem, the solution is to use a webworker and not the UI thread; it is both simple and lib-agnostic. anything else would require a bunch of fragile and/or clever hacks implemented in the codebase.

one thing that could work to improve performance is to allow RgbQuant to additionally accept a downscaled version of the main image, so that the palette building step is much less expensive. Depending on the content, the resulting palette is likely to be extremely similar. The reduction step would still be the same, though.

**Comment by jonnor** [comment]
The primary execution environment is Node.js, no WebWorkers there. Spawning a separate process is of course an option, through generally requires copying the data. We already downscale the images beforehand for performance...

```
while (!quant.isDone()) {
  quant.processChunk();
}
```
Typically this is implemented by letting the outermost processing loop(s) be able to do just one iteration, and then resume their work from another call entry.

**Comment by leeoniya** [comment]
If you have a server at your disposal, i would highly recommend delegating to a quantizer written in a low level language [1][2][3][etc] for performance. RgbQuant was originally designed for capturing dynamically generated *graphics* from canvas pixel data (where a server cannot be used cheaply due to latency, etc). For processing pre-existing static photographs/gradients and video frames, a server (and/or a process spawn) will do much better.

Hate to recommend the right tool for the right job, but there you go ;)

[1] http://www.ece.mcmaster.ca/~xwu/cq.c
[2] https://pngquant.org/
[3] http://www.graphicsmagick.org/api/quantize.html

**Comment by jonnor** [comment]
No worries, the recommendations are much appreciated!
